name: datadash

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          python -m playwright install --with-deps

      - name: Run script 23f3002495@ds.study.iitm.ac.in
        run: python sum_tables.py
